server {

    # Listen for incoming HTTP requests on port 80
    listen 8080;

    # Accept requests for any hostname
    server_name _;


    # ==========================================
    # React Frontend
    # ==========================================

    # React build files location
    root /usr/share/nginx/html;

    # Default file to serve
    index index.html;

    # Handle all frontend routes
    location / {

        # If the requested file exists, serve it.
        # Otherwise return index.html (required for React Router)
        try_files $uri $uri/ /index.html;

    }


   # ==========================================
# FastAPI Backend
# ==========================================

location /api/ {

    # Remove "/api" before forwarding the request
    rewrite ^/api/(.*)$ /$1 break;

    # Forward request to FastAPI -- it's a reverse proxy
    proxy_pass http://backend:8000;

    # Standard reverse proxy settings
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

}