interface RoastCardProps {
  roast: string;
}

export default function RoastCard({ roast }: RoastCardProps) {
  return (
    <div className="relative overflow-hidden rounded-2xl border border-violet-200 bg-gradient-to-br from-indigo-50 via-violet-50 to-purple-50 p-6 shadow-sm">
      <div className="absolute -top-4 -right-4 h-24 w-24 rounded-full bg-violet-200/40 blur-2xl" />
      <div className="relative">
        <div className="mb-3 flex items-center gap-2">
          <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-600 to-violet-600 text-sm text-white">
            AI
          </span>
          <h3 className="text-sm font-semibold tracking-wide text-violet-700 uppercase">
            AI Roast
          </h3>
        </div>
        <blockquote className="text-lg leading-relaxed font-medium text-slate-800">
          &ldquo;{roast}&rdquo;
        </blockquote>
        <p className="mt-3 text-xs text-violet-600/80">Generated by rule-based logic — no LLM harmed.</p>
      </div>
    </div>
  );
}
