name: Deploy to AWS EC2

on:
  workflow_run:
    workflows:
      - Build and Publish Docker Images
    types:
      - completed

jobs:
  deploy:
    # Only deploy if the publish workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            echo "=============================="
            echo "Changing project directory..."
            echo "=============================="

            cd ~/GitLens-AI

            echo "=============================="
            echo "Fetching latest code..."
            echo "=============================="

            git fetch origin
            git reset --hard origin/main

            echo "=============================="
            echo "Making deployment script executable..."
            echo "=============================="

            chmod +x scripts/deploy.sh

            echo "=============================="
            echo "Executing deployment script..."
            echo "=============================="

            ./scripts/deploy.sh "${{ github.event.workflow_run.head_sha }}"